const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function setup({nativeDecoder=false,gpu=false}={}){let now=0,id=0;const timers=new Map(),workers=[];class Worker{constructor(){this.sent=[];this.terminated=false;workers.push(this);}postMessage(message){this.sent.push(message);}terminate(){this.terminated=true;}reply(type,data={}){const request=this.sent.findLast(m=>m.id);this.onmessage({data:{id:request.id,type,data}});}}
 const staged=[];const nativeClient={cancel(){},request(){return Promise.resolve({});}};const scope={stageVoiceAssets:async options=>staged.push(options),createNativeDecoderClient:()=>nativeClient,Worker,AbortController,DOMException,URL,console,navigator:gpu?{gpu:{}}:{},setTimeout(fn,ms){const key=++id;timers.set(key,{fn,at:now+ms});return key;},clearTimeout(key){timers.delete(key);},AudioContext:class{constructor(){this.state='suspended';}async close(){this.state='closed';}}};vm.createContext(scope);vm.runInContext(fs.readFileSync(__dirname+'/../src/browser-voice.js','utf8').replaceAll('await import(CACHE_MODULE_URL)','({stageVoiceAssets:globalThis.stageVoiceAssets})').replaceAll('await import(NATIVE_MODULE_URL)','({createNativeDecoderClient:globalThis.createNativeDecoderClient})'),scope);
 const options={skipDefaultReference:true};if(nativeDecoder)options.nativeDecoder={prepare(){},decode(){},cancel(){}};
 return {voice:new scope.LeeWayBrowserVoice(options),workers,timers,staged,nativeClient,advance(ms){now+=ms;for(const [key,t]of [...timers])if(t.at<=now){timers.delete(key);t.fn();}}};}

test('continuous progress cannot extend the absolute preparation deadline',async()=>{const h=setup(),load=h.voice.load(),failure=assert.rejects(load,/15 minute|too long/);await tick();for(let i=0;i<14;i++){h.advance(60000);h.workers[0].reply('progress',{loaded:i});}h.advance(60000);await failure;assert.equal(h.voice.ready,false);assert.equal(h.workers[0].terminated,true);assert.equal(h.voice.pending.size,0);assert.equal(h.voice.loading,null);assert.equal(h.timers.size,0);});
test('cancel preparation rejects promptly and a fresh load survives old finally',async()=>{const h=setup(),old=h.voice.load(),failure=assert.rejects(old,{name:'AbortError'});await tick();await h.voice.cancelLoad();const fresh=h.voice.load();await tick();await failure;assert.equal(h.workers[0].terminated,true);assert.ok(h.voice.loading);h.workers[1].reply('complete',{device:'wasm'});await fresh;assert.equal(h.voice.ready,true);assert.equal(h.voice.pending.size,0);assert.equal(h.timers.size,0);});
test('partial load network failure cleans worker and does not redownload automatically',async()=>{const h=setup(),load=h.voice.load(),failure=assert.rejects(load,/Failed to fetch/);await tick();h.workers[0].reply('error',{message:'Failed to fetch',retryableGPU:false});await failure;assert.equal(h.workers.length,1);assert.equal(h.workers[0].terminated,true);assert.equal(h.voice.ready,false);assert.equal(h.voice.loading,null);});
test('specific GPU initialization failure retries once on a new CPU worker with visible warning',async()=>{const h=setup(),progress=[],load=h.voice.load(p=>progress.push(p));await tick();h.workers[0].reply('error',{message:'WebGPU shader compilation failed',retryableGPU:true});await tick();assert.equal(h.workers[0].terminated,true);assert.equal(h.workers.length,2);assert.equal(h.workers[1].sent[0].data.device,'wasm');assert.equal(h.staged.length,1);assert.equal(h.staged[0].signal.aborted,false);assert.ok(progress.some(p=>p.status==='warning'&&/downloading/.test(p.message)));h.workers[1].reply('complete',{device:'wasm'});await load;assert.equal(h.voice.ready,true);assert.equal(h.voice.device,'wasm');});
test('Android native decoder enters explicit CPU path when WebGPU is unavailable',async()=>{const h=setup({nativeDecoder:true,gpu:false}),load=h.voice.load();await tick();assert.equal(h.staged.length,1);assert.equal(h.staged[0].nativeDecoder,true);assert.equal(h.workers[0].sent[0].data.device,'wasm');assert.equal(h.workers[0].sent[0].data.nativeDecoder,true);h.workers[0].reply('complete',{device:'wasm',decoderBackend:'onnxruntime-android-cpu'});await load;assert.equal(h.voice.ready,true);assert.equal(h.voice.device,'wasm');});
test('Android WebGPU failure retries through native CPU decoder',async()=>{const h=setup({nativeDecoder:true,gpu:true}),load=h.voice.load();await tick();assert.equal(h.workers[0].sent[0].data.device,undefined);assert.equal(h.workers[0].sent[0].data.nativeDecoder,false);h.workers[0].reply('error',{message:'WebGPU shader compilation failed',retryableGPU:true});await tick();assert.equal(h.staged.length,1);assert.equal(h.staged[0].nativeDecoder,true);assert.equal(h.workers[1].sent[0].data.device,'wasm');assert.equal(h.workers[1].sent[0].data.nativeDecoder,true);h.workers[1].reply('complete',{device:'wasm',decoderBackend:'onnxruntime-android-cpu'});await load;assert.equal(h.voice.ready,true);});

test('failed CPU retry terminates and does not loop',async()=>{const h=setup(),load=h.voice.load(),failure=assert.rejects(load,/CPU failed/);await tick();h.workers[0].reply('error',{message:'WebGPU shader error',retryableGPU:true});await tick();h.workers[1].reply('error',{message:'CPU failed',retryableGPU:true});await failure;assert.equal(h.workers.length,2);assert.equal(h.workers[1].terminated,true);});
async function workerError(message){const replies=[];const scope={URL,console,Float32Array,performance,self:{location:{href:'https://example.test/worker.js'},addEventListener(){},navigator:{gpu:{requestAdapter:async()=>({features:new Set()})}},postMessage:value=>replies.push(value)},env:{backends:{onnx:{wasm:{},webgpu:{}}}},AutoProcessor:{from_pretrained:async()=>({})},ChatterboxModel:{from_pretrained:async()=>{throw new Error(message)}},InterruptableStoppingCriteria:class{interrupt(){}},fetch:async()=>({ok:true,json:async()=>({})})};scope.navigator=scope.self.navigator;vm.createContext(scope);const source=fs.readFileSync(__dirname+'/../src/chatterbox.worker.js','utf8').replace(/^import .*;\r?\n/gm,'');vm.runInContext(source,scope);scope.self.onmessage({data:{id:1,type:'load',data:{}}});await tick();return replies.find(r=>r.type==='error').data;}
test('worker classifies GPU compilation only; network mentioning WebGPU does not retry',async()=>{assert.equal((await workerError('WebGPU shader compile failed')).retryableGPU,true);assert.equal((await workerError('Failed to fetch WebGPU model')).retryableGPU,false);assert.equal((await workerError('HTTP404 missing shader file')).retryableGPU,false);assert.equal((await workerError('Unknown model')).retryableGPU,false);});
