const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const api=import('data:text/javascript;base64,'+fs.readFileSync(__dirname+'/../src/studio-audio.js').toString('base64'));
const rate=16000;
const tone=(hz,seconds=1,amp=.2)=>Float32Array.from({length:rate*seconds},(_,i)=>amp*Math.sin(2*Math.PI*hz*i/rate));
const rms=a=>Math.sqrt(a.reduce((s,x)=>s+x*x,0)/a.length);
function frequency(a){let crossings=0;const start=Math.floor(a.length*.15),end=Math.floor(a.length*.85);for(let i=start+1;i<end;i++)if(a[i-1]<=0&&a[i]>0)crossings++;return crossings*rate/(end-start);}
async function render(audio,t={}){return (await api).renderAudio({audio,sampleRate:rate},t);}
test('normalization bounds every setting and rejects nonfinite or coerced values',async()=>{const {normalizeTuning,DEFAULT_TUNING}=await api;assert.deepEqual(normalizeTuning(),DEFAULT_TUNING);const t=normalizeTuning({pace:100,pitch:-100,bass:NaN,gain:'6',air:Infinity});assert.equal(t.pace,1.6);assert.equal(t.pitch,-6);assert.equal(t.bass,0);assert.equal(t.gain,0);assert.equal(t.air,0);});
test('pace changes rendered duration and WAV frames while preserving fundamental',async()=>{const result=await render(tone(440),{pace:1.4});assert.ok(Math.abs(result.metrics.durationSeconds-1/1.4)<1/rate);assert.ok(Math.abs(frequency(result.audio)-440)<8);const wav=new DataView(await result.blob.arrayBuffer());assert.equal(wav.getUint32(40,true),result.audio.length*2);assert.equal(wav.getUint32(24,true),rate);assert.equal(result.blob.type,'audio/wav');});
test('pitch changes fundamental independently from pace and duration',async()=>{for(const pitch of [-6,6]){const result=await render(tone(440),{pitch,pace:1.2});assert.ok(Math.abs(result.metrics.durationSeconds-1/1.2)<1/rate);assert.ok(Math.abs(frequency(result.audio)-440*2**(pitch/12))<12);}});
test('bass and presence are audible spectral controls encoded into PCM',async()=>{for(const [hz,key] of [[100,'bass'],[2800,'presence'],[450,'warmth'],[6500,'air']]){const a=await render(tone(hz),{[key]:-9}),b=await render(tone(hz),{[key]:9});assert.ok(rms(b.audio)>rms(a.audio)*1.5,key);}});
test('highpass attenuates low rumble',async()=>{const a=await render(tone(60),{highpass:40}),b=await render(tone(60),{highpass:180});assert.ok(rms(b.audio)<rms(a.audio)*.25);});
test('de-esser attenuates high-frequency energy; low-level expansion and compression act',async()=>{let a=await render(tone(6000)),b=await render(tone(6000),{deEss:1});assert.ok(rms(b.audio)<rms(a.audio)*.95);a=await render(tone(440,1,.001));b=await render(tone(440,1,.001),{noiseReduction:1});assert.ok(rms(b.audio)<rms(a.audio)*.6);a=await render(tone(440,1,.8));b=await render(tone(440,1,.8),{compression:4});assert.ok(rms(b.audio)<rms(a.audio)*.5);});
test('gain changes output without normalization erasing differences; peak guard prevents clipping',async()=>{const a=await render(tone(440),{gain:-6}),b=await render(tone(440),{gain:6});assert.ok(rms(b.audio)>rms(a.audio)*3.9);const c=await render(tone(100,1,.95),{bass:9,gain:6});assert.ok(c.metrics.samplePeak<=.980001);assert.ok(c.metrics.peakGuardGainDb<0);});
test('silence and malformed samples produce finite output',async()=>{const a=await render(new Float32Array(rate),{pace:.6,pitch:6});assert.equal(a.metrics.samplePeak,0);assert.ok(a.audio.every(Number.isFinite));const b=await render(new Float32Array([NaN,Infinity,-Infinity,0,.1]));assert.ok(b.audio.every(Number.isFinite));});
test('invalid and excessive input/output sizes are rejected before processing',async()=>{const {renderAudio}=await api;await assert.rejects(()=>renderAudio({audio:new Float32Array(0),sampleRate:rate}),RangeError);await assert.rejects(()=>renderAudio({audio:tone(440),sampleRate:0}),RangeError);await assert.rejects(()=>renderAudio({audio:new Float32Array(rate*109),sampleRate:rate},{pace:.6}),RangeError);await assert.rejects(()=>renderAudio({audio:new Float32Array(rate*181),sampleRate:rate}),RangeError);});
