const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function deferred(){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};}
function setup({audio=async()=>new Blob([new Uint8Array([2])]),fetcher=async()=>({ok:true,blob:async()=>new Blob([new Uint8Array([3])]),arrayBuffer:async()=>new Uint8Array([3]).buffer,headers:{get:()=>null}})}={}){
 const elements=new Map(),decoded=[],renders=[];let offlineCount=0,onlineCount=0;
 const element=id=>{if(!elements.has(id))elements.set(id,{id,textContent:'',value:'',checked:false,paused:true,ended:false,duration:1,currentTime:0,disabled:false,style:{setProperty(){}},classList:{toggle(){}},setAttribute(k,v){this[k]=v;},removeAttribute(k){delete this[k];},addEventListener(){},append(){},replaceChildren(){},querySelector:s=>element(id+s),getBoundingClientRect:()=>({height:200}),pause(){this.paused=true;},load(){},async play(){this.paused=false;},focus(){}});return elements.get(id);};
 element('runtime').value='browser';
 class Offline{constructor(){offlineCount++;}async decodeAudioData(bytes){const marker=new Uint8Array(bytes)[0];decoded.push(marker);return {length:16,sampleRate:24000,duration:16/24000,numberOfChannels:1,getChannelData:()=>new Float32Array(16).fill(marker/10)};}}
 const scope={console,Blob,Float32Array,ArrayBuffer,AbortController,DOMException,setTimeout,clearTimeout,crypto:globalThis.crypto,URL:Object.assign(class extends URL {},{createObjectURL:()=>`blob:fixture`,revokeObjectURL(){}}),OfflineAudioContext:Offline,webkitOfflineAudioContext:Offline,DEFAULT_TUNING:{pace:1},normalizeTuning:t=>t,document:{getElementById:element,querySelector:element,createElement:element,documentElement:element('html'),body:element('body')},localStorage:{getItem:()=>null,setItem(){}},ResizeObserver:class{observe(){}},addEventListener(){},fetch:fetcher,voiceRegistry:{audio,save:async()=>{},list:async()=>[]},LeeWayBrowserVoice:class{constructor(){this.ready=false;}stop(){}async audioContext(){onlineCount++;throw new Error('Real-time AudioContext must not gate previews');}}};
 vm.createContext(scope);const source=fs.readFileSync(__dirname+'/../src/studio.js','utf8').replace(/^import .*;\r?\n/gm,'').replace(/import\.meta\.url/g,JSON.stringify('https://example.test/src/studio.js')).replace(/^refresh\(\)\.then\(.*$/gm,'');vm.runInContext(source,scope);
 scope.recordRender=raw=>{renders.push(raw);return {audio:raw.audio,sampleRate:raw.sampleRate,blob:new Blob(['wav'])};};vm.runInContext('renderOffThread=async (raw)=>recordRender(raw);',scope);
 return {scope,element,decoded,renders,read:code=>vm.runInContext(code,scope),run:code=>vm.runInContext(code,scope),counts:()=>({offlineCount,onlineCount})};
}
const custom={id:'custom-speaker',name:'Custom Speaker',provider:'chatterbox',source:'USER_LOCAL'};
function profiles(h,items){h.scope.profiles=items;h.run('packages=profiles;');}

test('selecting a reference profile decodes offline and renders an immediately playable tuning take',async()=>{const h=setup();profiles(h,[custom]);await h.run("select('custom-speaker')");assert.equal(h.renders.length,1);assert.equal(h.counts().onlineCount,0);assert.equal(h.counts().offlineCount,1);assert.equal(h.element('playPause').disabled,false);assert.match(h.read('rawLabel'),/Reference recording/);assert.equal(h.read('raw.audio[0]')>.19,true);});

test('late reference selection cannot replace the newly selected speaker or its rendered take',async()=>{const first=deferred();const h=setup({audio:id=>id==='custom-speaker'?first.promise:Promise.resolve(new Blob([new Uint8Array([7])]))});profiles(h,[custom,{...custom,id:'second-speaker',name:'Second Speaker'}]);const old=h.run("select('custom-speaker')");await h.run("select('second-speaker')");first.resolve(new Blob([new Uint8Array([2])]));await old;assert.equal(h.read('selected.id'),'second-speaker');assert.equal(h.renders.length,1);assert.ok(h.read('raw.audio[0]')>.69);});

test('Agent Lee preview becomes playable while its clone reference is still pending',async()=>{const pending=deferred(),h=setup({audio:()=>pending.promise});profiles(h,[{...custom,id:'agent-lee-voice-one',name:'Agent Lee'}]);const selecting=h.run("select('agent-lee-voice-one')");await tick();await tick();assert.equal(h.element('playPause').disabled,false);assert.equal(h.renders.length,1);assert.match(h.read('rawLabel'),/Speaker preview/);pending.resolve(new Blob([new Uint8Array([8])]));await selecting;await tick();assert.equal(h.renders.length,1,'reference arrival must not overwrite the prepared preview');});

test('preview HTTP failure gives a visible unavailable result without fabricated audio',async()=>{const h=setup({fetcher:async()=>({ok:false,status:404})});profiles(h,[{id:'kokoro-af_heart',voiceId:'af_heart',name:'Heart',provider:'kokoro'}]);await h.run("select('kokoro-af_heart')");assert.equal(h.renders.length,0);assert.equal(h.element('playPause').disabled,true);assert.match(h.element('renderState').textContent,/unavailable|failed|not ready/i);});

test('late preview response cannot change a newer selected reference',async()=>{const pending=deferred(),h=setup({fetcher:()=>pending.promise});profiles(h,[{id:'kokoro-af_heart',voiceId:'af_heart',name:'Heart',provider:'kokoro'},custom]);const old=h.run("select('kokoro-af_heart')");await h.run("select('custom-speaker')");pending.resolve({ok:true,blob:async()=>new Blob([new Uint8Array([9])]),arrayBuffer:async()=>new Uint8Array([9]).buffer,headers:{get:()=>null}});await old;assert.equal(h.read('selected.id'),'custom-speaker');assert.equal(h.renders.length,1);assert.ok(h.read('raw.audio[0]')<.3);});

test('text and synthesis changes preserve the ready audition while marking new generation pending',async()=>{const h=setup();profiles(h,[custom]);await h.run("select('custom-speaker')");const before=h.read('raw'),take=h.read('rendered');h.element('speechText').oninput();assert.equal(h.read('raw'),before);assert.equal(h.read('rendered'),take);assert.equal(h.element('playPause').disabled,false);h.run("pendingSynthesis('Synthesis settings changed.')");assert.equal(h.read('raw'),before);assert.equal(h.read('rendered'),take);});

test('editing text during a pending preview does not invalidate the pending audio',async()=>{const pending=deferred(),h=setup({audio:()=>pending.promise});profiles(h,[custom]);const selection=h.run("select('custom-speaker')");h.element('speechText').oninput();pending.resolve(new Blob([new Uint8Array([2])]));await selection;assert.equal(h.renders.length,1);assert.equal(h.element('playPause').disabled,false);});

test('a timed-out preview reports retry and selecting the same profile again recovers Play',async()=>{
 let calls=0;const h=setup({fetcher:async(_url,{signal})=>{calls++;if(calls===1)return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(new DOMException('Timed out','AbortError')),{once:true}));return {ok:true,blob:async()=>new Blob([new Uint8Array([4])])};}});
 const timers=new Map();let timerId=0;h.scope.setTimeout=(fn,ms)=>{timers.set(++timerId,{fn,ms});return timerId;};h.scope.clearTimeout=id=>timers.delete(id);
 profiles(h,[{id:'kokoro-af_bella',voiceId:'af_bella',name:'Bella',provider:'kokoro'}]);const loading=h.run("select('kokoro-af_bella')");assert.equal(timers.size,1);const timeout=[...timers.values()][0];assert.equal(timeout.ms,15000);timeout.fn();await loading;
 assert.equal(h.element('playPause').disabled,true);assert.match(h.element('renderState').textContent,/timed out.*retry/i);assert.equal(timers.size,0);
 await h.run("select('kokoro-af_bella')");assert.equal(h.element('playPause').disabled,false);assert.equal(h.renders.length,1);assert.equal(calls,2);assert.equal(timers.size,0);
});

test('a failed old preview cannot overwrite a newly ready profile status',async()=>{
 const pending=deferred(),h=setup({fetcher:()=>pending.promise});profiles(h,[{id:'kokoro-af_heart',voiceId:'af_heart',name:'Heart',provider:'kokoro'},custom]);const old=h.run("select('kokoro-af_heart')");await h.run("select('custom-speaker')");const readyText=h.element('status').textContent;pending.reject(new Error('Obsolete preview failed'));await old;assert.equal(h.element('status').textContent,readyText);assert.equal(h.element('playPause').disabled,false);assert.equal(h.renders.length,1);
});
