/* REGION: LEEWAY.VOICE.QUALIFICATION; TAG: DEVICE_HAS_NO_SPEAKER_AUTHORITY
WHO: LeeWay qualification. WHAT: Test existing Voice core/runtime with explicit fixture bindings/providers.
WHEN: Before live admission. WHERE: Node unit behavior, not physical audibility.
WHY: Silent defaults, provider substitution and stale selection are not portability.
HOW: Execute real resolver/render functions; fixtures never become customer voice approval. LICENSE: MIT */
const {test,before}=require('node:test');const assert=require('node:assert/strict');
let core,gate;
before(async()=>{core=await import('../src/voice-package-core.js');gate=await import('../runtime/persona-voice-gate.mjs');});
function fixture(){return{bindings:{authority:'LEEWAY_VOICE_FABRIC',bindings:{'agent-lee':{agentId:'agent-lee',personaFamily:'AGENT_LEE_CONSTITUTIONAL',personaArchetypeId:'ELDER_MALE',voicePackageId:'kokoro-test',state:'VERIFIED_CATALOG_SELECTION',selectedBy:'CREATOR'}}},catalog:{packages:[{id:'kokoro-test',provider:'kokoro',voiceId:'test',speakerId:'kokoro-test',status:'AVAILABLE'}]}};}
function audio(){const b=Buffer.alloc(48);b.write('RIFF');b.writeUInt32LE(40,4);b.write('WAVE',8);return{audioContent:b.toString('base64'),format:'wav',provider:'kokoro',voicePackageId:'kokoro-test',voiceId:'test'};}
const read=f=>()=>gate.voiceSelectionSnapshot(f);
test('explicit Voice Fabric record resolves with no device identity input',()=>{const selected=core.resolveAgentVoiceSelection(fixture());assert.equal(selected.voicePackageId,'kokoro-test');assert.equal(selected.deviceMayOverride,false);assert.equal(selected.systemVoiceFallback,false);assert.equal(Object.isFrozen(selected),true);});
test('missing record never invents a default voice',()=>{const f=fixture();delete f.bindings.bindings['agent-lee'];assert.throws(()=>core.resolveAgentVoiceSelection(f),/VOICE_SELECTION_REQUIRED/)});
test('PC or phone cannot declare themselves Voice authority',()=>{const f=fixture();f.bindings.authority='WINDOWS';assert.throws(()=>core.resolveAgentVoiceSelection(f),/VOICE_FABRIC_AUTHORITY_REQUIRED/)});
test('wrong agent cannot borrow another voice identity',()=>{const f=fixture();f.bindings.bindings['agent-lee'].agentId='other';assert.throws(()=>core.resolveAgentVoiceSelection(f),/VOICE_AGENT_IDENTITY_MISMATCH/)});
test('persona fields must be explicit, not supplied by device defaults',()=>{for(const field of ['personaFamily','personaArchetypeId','voicePackageId']){const f=fixture();delete f.bindings.bindings['agent-lee'][field];assert.throws(()=>core.resolveAgentVoiceSelection(f),/VOICE_BINDING_INCOMPLETE/)}});
test('unapproved selection cannot become production approval',()=>{const f=fixture();f.bindings.bindings['agent-lee'].selectedBy='DEVICE_DEFAULT';assert.throws(()=>core.resolveAgentVoiceSelection(f),/CREATOR_VOICE_SELECTION_REQUIRED/)});
test('temporary audition selection stays non-production',()=>{const f=fixture();Object.assign(f.bindings.bindings['agent-lee'],{state:'TEMPORARY_VERIFIED_PROVIDER',selectedBy:'CREATOR_PENDING_FINAL_AUDITION'});const r=core.resolveAgentVoiceSelection(f);assert.equal(r.qualificationOnly,true);assert.equal(r.productionAdmitted,false)});
test('catalog ambiguity fails before synthesis',()=>{const f=fixture();f.catalog.packages.push({...f.catalog.packages[0]});assert.throws(()=>core.resolveAgentVoiceSelection(f),/VOICE_PACKAGE_MISSING_OR_AMBIGUOUS/)});
test('Android TTS cannot replace the selected Agent Lee engine',()=>{const f=fixture();f.catalog.packages[0].provider='android-tts';assert.throws(()=>core.resolveAgentVoiceSelection(f),/DEVICE_TTS_NOT_AGENT_VOICE/)});
test('unavailable selected package is not replaced by a healthy alternative',()=>{const f=fixture();f.catalog.packages[0].status='OFFLINE';assert.throws(()=>core.resolveAgentVoiceSelection(f),/VOICE_PACKAGE_UNAVAILABLE/)});
test('provider speaker identifier is mandatory',()=>{const f=fixture();delete f.catalog.packages[0].voiceId;assert.throws(()=>core.resolveAgentVoiceSelection(f),/VOICE_PROVIDER_SPEAKER_REQUIRED/)});
test('synthesis forwards exact prepared text and preserves persona metadata',async()=>{const f=fixture();const text='Yo, what it is. The device report is ready.';let received;const r=await gate.renderBoundAgentSpeech({text,resolveSelection:read(f),providers:{kokoro:async req=>(received=req,audio())}});assert.equal(received.text,text);assert.equal(received.voiceId,'test');assert.equal(r.personaFamily,'AGENT_LEE_CONSTITUTIONAL');assert.equal(r.textHash,gate.sha256(text));assert.equal(r.state,'SYNTHESIZED_NOT_PLAYBACK_VERIFIED')});
test('missing executor cannot invoke a different provider',async()=>{let calls=0;await assert.rejects(()=>gate.renderBoundAgentSpeech({text:'Test',resolveSelection:read(fixture()),providers:{chatterbox:async()=>{calls++;return audio()}}}),/SELECTED_VOICE_PROVIDER_UNBOUND/);assert.equal(calls,0)});
test('provider failure preserves selection and performs no fallback',async()=>{const f=fixture();const revision=read(f)().selectionRevision;let fallback=0;await assert.rejects(()=>gate.renderBoundAgentSpeech({text:'Test',resolveSelection:read(f),providers:{kokoro:async()=>{throw Error('WORKER_OFFLINE')},chatterbox:async()=>{fallback++;return audio()}}}),/WORKER_OFFLINE/);assert.equal(read(f)().selectionRevision,revision);assert.equal(fallback,0)});
test('returned wrong speaker is rejected',async()=>{await assert.rejects(()=>gate.renderBoundAgentSpeech({text:'Test',resolveSelection:read(fixture()),providers:{kokoro:async()=>({...audio(),voiceId:'another'})}}),/VOICE_RENDERER_IDENTITY_MISMATCH/)});
test('returned different package or system provider is rejected',async()=>{for(const patch of [{voicePackageId:'other'},{provider:'android-tts'}])await assert.rejects(()=>gate.renderBoundAgentSpeech({text:'Test',resolveSelection:read(fixture()),providers:{kokoro:async()=>({...audio(),...patch})}}),/VOICE_RENDERER_IDENTITY_MISMATCH/)});
test('selection change during synthesis cannot publish stale audio',async()=>{const f=fixture();await assert.rejects(()=>gate.renderBoundAgentSpeech({text:'Test',resolveSelection:read(f),providers:{kokoro:async()=>{f.bindings.bindings['agent-lee'].personaArchetypeId='YOUNG_MALE';return audio()}}}),/STALE_VOICE_SELECTION_AUDIO_REJECTED/)});
test('empty or malformed audio is not accepted as speech',async()=>{for(const content of ['',Buffer.from('not audio').toString('base64')])await assert.rejects(()=>gate.renderBoundAgentSpeech({text:'Test',resolveSelection:read(fixture()),providers:{kokoro:async()=>({...audio(),audioContent:content})}}),/VOICE_AUDIO/)});
test('empty or overlong text fails without provider invocation',async()=>{let calls=0;for(const text of ['','x'.repeat(1501)])await assert.rejects(()=>gate.renderBoundAgentSpeech({text,resolveSelection:read(fixture()),providers:{kokoro:async()=>{calls++;return audio()}}}),/VOICE_PREPARED_TEXT_INVALID/);assert.equal(calls,0)});
