import {voiceRegistry} from './voice-registry.js';
import {DEFAULT_TUNING,normalizeTuning} from './studio-audio.js';
const $=id=>document.getElementById(id), Voice=globalThis.LeeWayBrowserVoice;
const voice=new Voice({skipDefaultReference:true});
const synthDefaults={exaggeration:.5,temperature:.8,top_p:.95,top_k:50};
const controls=[['pace','Pace',.6,1.6,.01,'×','Independent tempo; 1.15 is 15% faster.'],['pitch','Pitch',-6,6,.1,'st','Shift pitch independently of tempo.'],['bass','Bass',-9,9,.5,'dB','Low-frequency weight.'],['warmth','Warmth',-9,9,.5,'dB','Low-mid body.'],['presence','Presence',-9,9,.5,'dB','Speech definition.'],['air','Air',-9,9,.5,'dB','High-frequency brightness.'],['highpass','Low cut',40,180,5,'Hz','Reduce low rumble.'],['deEss','De-essing',0,1,.05,'','Tame sharp consonants.'],['noiseReduction','Noise reduction',0,1,.05,'','Gentle low-level expansion. Strong settings can soften word endings.'],['compression','Compression',1,4,.1,':1','Even out vocal dynamics.'],['gain','Output gain',-9,6,.5,'dB','Adjust final level.']];
const synthControls=[['exaggeration','Expression',0,1,.05,'','Style exaggeration.'],['temperature','Temperature',.5,1,.01,'','Sampling variation.'],['top_p','Top P · unavailable',.5,1,.01,'','Unsupported by the pinned browser runtime; this control is disabled.'],['top_k','Top K',10,100,1,'','Sampling candidate count.']];
let packages=[],hosted=[],selected=null,referenceBlob=null,raw=null,rendered=null,tuning={...DEFAULT_TUNING},synthesis={...synthDefaults},epoch=0,selectionEpoch=0,renderEpoch=0,busy=false,preparing=false,renderTimer,referenceURL,outputURL,renderWorker,renderReject;
const isHosted=()=>!!selected?.voiceUuid;
const status=(message,error=false)=>{$('status').textContent=message;$('status').classList.toggle('error',error);};
const safeRead=key=>{try{return JSON.parse(localStorage.getItem(key));}catch{return null;}};
function persist(){try{localStorage.setItem('leeway-studio-selected',JSON.stringify(selected?.id));if(selected)localStorage.setItem(`leeway-studio:${selected.id}`,JSON.stringify({tuning,synthesis}));}catch{status('Browser storage is unavailable. Export your package to preserve it.');}}
function buttons(){ $('generate').disabled=!selected||busy||preparing||(!isHosted()&&!voice.ready);$('prepare').disabled=isHosted()||preparing||voice.ready;$('prepare').textContent=voice.ready?'Browser model ready':'Prepare browser model';$('generate').textContent=isHosted()?'Generate with Resemble · uses account credits':'Generate audition';$('download').disabled=!rendered||busy;$('saveCopy').disabled=!selected||!referenceBlob||isHosted();$('exportVoice').disabled=!selected;$('removeVoice').disabled=!selected||!['USER_LOCAL','RESEMBLE_HOSTED'].includes(selected.source);for(const [key]of synthControls){$(key).disabled=isHosted()||key==='top_p'||(key==='exaggeration'&&voice.capabilities?.exaggeration===false);$(`${key}Number`).disabled=isHosted()||key==='top_p'||(key==='exaggeration'&&voice.capabilities?.exaggeration===false);}}
function stopRender(){if(renderWorker){renderWorker.terminate();renderWorker=null;renderReject?.(new DOMException('Rendering cancelled','AbortError'));renderReject=null;}}
function renderOffThread(raw,tuning){stopRender();return new Promise((resolve,reject)=>{renderReject=reject;const worker=renderWorker=new Worker(new URL('./studio-render.worker.js',import.meta.url),{type:'module'});worker.onmessage=({data})=>{worker.terminate();renderWorker=null;renderReject=null;data.error?reject(new Error(data.error)):resolve(data.result);};worker.onerror=()=>{worker.terminate();renderWorker=null;renderReject=null;reject(new Error('Audio processing worker failed.'));};worker.postMessage({raw,tuning});});}
function stopMedia(){voice.stop();$('outputPlayer').pause();$('referencePlayer').pause();}
function invalidate(message){++epoch;++renderEpoch;clearTimeout(renderTimer);stopRender();stopMedia();busy=false;raw=null;rendered=null;if(outputURL)URL.revokeObjectURL(outputURL);outputURL=null;$('outputPlayer').removeAttribute('src');$('outputPlayer').load();$('renderState').textContent=message;buttons();}
function createControls(items,parent,kind){for(const [key,label,min,max,step,unit,hint]of items){const box=document.createElement('div');box.className='control';box.innerHTML=`<div class="control-heading"><label for="${key}">${label} <span class="hint">${unit}</span></label><input id="${key}Number" type="number" min="${min}" max="${max}" step="${step}" aria-label="${label} value"></div><input id="${key}" type="range" min="${min}" max="${max}" step="${step}"><p class="hint">${hint}</p>`;$(parent).append(box);for(const suffix of ['', 'Number'])$(key+suffix).addEventListener('input',event=>{if(event.target.value===''||!Number.isFinite(Number(event.target.value)))return;const value=Math.max(min,Math.min(max,Number(event.target.value)));(kind==='dsp'?tuning:synthesis)[key]=value;$(key).value=value;$(`${key}Number`).value=value;persist();if(kind==='dsp'){++renderEpoch;rendered=null;$('outputPlayer').pause();buttons();if(raw){$('renderState').textContent='Updating acoustic processing…';clearTimeout(renderTimer);renderTimer=setTimeout(()=>rerender().catch(fail),180);}}else invalidate('Synthesis settings changed. Generate a fresh audition.');});}}
function fillControls(){for(const [key]of controls){$(key).value=tuning[key];$(`${key}Number`).value=tuning[key];}for(const [key]of synthControls){$(key).value=synthesis[key];$(`${key}Number`).value=synthesis[key];}}
function drawList(){const query=$('search').value.toLowerCase();$('voiceList').replaceChildren();const all=[...new Map([...packages,...hosted].map(pkg=>[pkg.id,pkg])).values()];$('voiceCount').textContent=String(all.length);for(const pkg of all){if(![pkg.name,pkg.id,pkg.gender,pkg.provider,pkg.source].join(' ').toLowerCase().includes(query))continue;const button=document.createElement('button');button.className='voice-card';button.setAttribute('aria-pressed',String(pkg.id===selected?.id));const title=document.createElement('strong');title.textContent=pkg.name;const subtitle=document.createElement('small');const same=all.some(other=>other.id!==pkg.id&&pkg.referenceUrl&&pkg.referenceUrl===other.referenceUrl);subtitle.textContent=`${pkg.gender||'Gender unspecified'} · ${pkg.provider} · ${pkg.voiceUuid?'Hosted account voice':pkg.source==='DELIVERY_PRESET'?'Delivery preset / same default speaker':'Reference speaker'}\n${pkg.id}`;button.append(title,subtitle);button.onclick=()=>select(pkg.id).catch(fail);$('voiceList').append(button);}}
async function refresh(id){packages=await voiceRegistry.list();drawList();const next=id||selected?.id||safeRead('leeway-studio-selected');await select([...packages,...hosted].find(p=>p.id===next)?.id||packages[0]?.id);}
async function select(id){const pkg=[...packages,...hosted].find(p=>p.id===id);if(!pkg)return;selected=pkg;referenceBlob=null;invalidate('No generated audition for this selection.');const token=++selectionEpoch;const saved=safeRead(`leeway-studio:${id}`);tuning=normalizeTuning({...DEFAULT_TUNING,pace:pkg.pace??1,...pkg.tuning,...saved?.tuning});synthesis={...synthDefaults,exaggeration:pkg.exaggeration??.5,...pkg.synthesis,...saved?.synthesis};fillControls();persist();drawList();$('selectedTitle').textContent=pkg.name;$('selectedMeta').textContent=`${pkg.id} · ${pkg.provider} · ${pkg.gender||'Gender unspecified'}`;$('selectedDescription').textContent=pkg.description||'';$('sourceInfo').textContent=`Source: ${pkg.source||'User reference'}${pkg.referenceSha256?' · SHA-256: '+pkg.referenceSha256:''}`;$('modelState').textContent=isHosted()?'Hosted synthesis uses your connected Resemble account. Local Chatterbox sampling controls do not apply.':voice.ready?'Browser model loaded. The selected speaker reference is applied before each generation.':'First model download approximately 1.5 GB. Prepare explicitly to begin.';$('integrationCode').textContent=`import {voiceRegistry} from './src/voice-registry.js';\n// Import the portable JSON file on the target host:\nconst profile = await voiceRegistry.importPortable(packageJSON);\nconst reference = await voiceRegistry.audio(profile.id);\n// Apply profile.tuning with studio-audio.js after synthesis.\n// Selected profile ID: ${pkg.id}`;if(referenceURL)URL.revokeObjectURL(referenceURL);referenceURL=null;$('referencePlayer').removeAttribute('src');$('referencePlayer').load();buttons();status(`Selected ${pkg.name}.`);if(isHosted()){await voiceRegistry.save(pkg,null);if(token!==selectionEpoch)return;if(pkg.previewUrl)$('referencePlayer').src=pkg.previewUrl;return;}const blob=await voiceRegistry.audio(id);if(token!==selectionEpoch)return;if(!blob)throw new Error('This profile has no reference audio. Import its portable package again.');referenceBlob=blob;referenceURL=URL.createObjectURL(blob);$('referencePlayer').src=referenceURL;buttons();}
async function rerender(){if(!raw)return;const token=++renderEpoch;const generation=epoch;const result=await renderOffThread(raw,normalizeTuning(tuning));if(token!==renderEpoch||generation!==epoch)return;rendered=result;if(outputURL)URL.revokeObjectURL(outputURL);outputURL=URL.createObjectURL(result.blob);$('outputPlayer').src=outputURL;$('renderState').textContent=`Ready · ${(result.audio.length/result.sampleRate).toFixed(1)} seconds · ${result.sampleRate.toLocaleString()} Hz · current acoustic settings rendered into WAV. Press play to audition.`;buttons();}
async function api(url,options){const response=await fetch(url,options);if(!response.ok){if(response.status===404)throw new Error('Hosted adapter unavailable. Start the optional Python studio server with RESEMBLE_API_KEY configured; static hosting supports local voices only.');let message;try{message=(await response.json()).error;}catch{}throw new Error(message||`Provider request failed (${response.status}).`);}return response.json();}
async function generate(){if(!selected||busy)return;const text=$('speechText').value.trim();if(!text)throw new Error('Enter some audition text.');invalidate('Generating a new audition…');const token=epoch;busy=true;buttons();try{if(isHosted()){status('Generating with Resemble. This uses your account credits.');const result=await api('/api/resemble/synthesize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({voiceUuid:selected.voiceUuid,text})});if(token!==epoch)return;const bytes=Uint8Array.from(atob(result.audioContent),c=>c.charCodeAt(0));const context=await voice.audioContext();const decoded=await context.decodeAudioData(bytes.buffer);if(token!==epoch)return;const audio=new Float32Array(decoded.length);for(let c=0;c<decoded.numberOfChannels;c++){const channel=decoded.getChannelData(c);for(let i=0;i<audio.length;i++)audio[i]+=channel[i]/decoded.numberOfChannels;}raw={audio,sampleRate:decoded.sampleRate};}else{if(!voice.ready)throw new Error('Prepare the browser model first.');if(!referenceBlob)throw new Error('Wait for the selected reference recording to load.');await voice.setReference(referenceBlob);if(token!==epoch)return;const chunks=Voice.chunks(text);if(chunks.length>60)throw new Error('Use a shorter audition text.');const parts=[];let sampleRate;for(let i=0;i<chunks.length;i++){status(`Generating ${selected.name} · segment ${i+1} of ${chunks.length}…`);const result=await voice.request('generate',{text:chunks[i],...synthesis});if(token!==epoch)return;if(sampleRate&&sampleRate!==result.sampleRate)throw new Error('Generated segments have inconsistent sample rates.');sampleRate=result.sampleRate;parts.push(result.audio instanceof Float32Array?result.audio:new Float32Array(result.audio));}const audio=new Float32Array(parts.reduce((n,p)=>n+p.length,0));let offset=0;for(const part of parts){audio.set(part,offset);offset+=part.length;}raw={audio,sampleRate};}if(token!==epoch)return;await rerender();if(token===epoch)status('Audition ready. Press play to hear it, then tune or download.');}finally{if(token===epoch){busy=false;buttons();}}}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function validateReference(file){if(!file||file.size<1||file.size>15_000_000)throw new Error('Choose a reference audio file smaller than 15 MB.');const context=await voice.audioContext();let decoded;try{decoded=await context.decodeAudioData(await file.arrayBuffer());}catch{throw new Error('This audio format could not be decoded. Try WAV or MP3.');}if(decoded.duration<1||decoded.duration>30)throw new Error('Reference audio must be between 1 and 30 seconds.');return file;}
const freshId=name=>String(name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)+'-'+crypto.randomUUID().slice(0,8);
function fail(error){if(error.name!=='AbortError')status(error.message||String(error),true);buttons();}
function action(id,handler){$(id).onclick=()=>Promise.resolve().then(handler).catch(fail);}
createControls(controls,'dspControls','dsp');createControls(synthControls,'synthesisControls','synth');fillControls();
$('search').oninput=drawList;$('speechText').oninput=()=>invalidate('Text changed. Generate a fresh audition.');
action('prepare',async()=>{preparing=true;buttons();$('modelProgress').hidden=false;try{await voice.load(progress=>{const text=progress.message||`${progress.status||'Loading'} ${progress.file||'browser model'}`;status(text);if(Number.isFinite(progress.progress)){$('modelProgress').max=100;$('modelProgress').value=progress.progress;}else $('modelProgress').removeAttribute('value');});$('modelState').textContent=`Browser model ready · ${voice.device||'local inference'}.`;status('Model ready. Choose a speaker and generate an audition.');}finally{preparing=false;$('modelProgress').hidden=true;buttons();}});
action('generate',generate);
action('loadTake',async()=>{const file=$('takeFile').files[0];if(!file||file.size>64000000)throw new Error('Choose an audio take smaller than 64 MB.');invalidate('Loading existing recording…');const token=epoch;const context=await voice.audioContext();const decoded=await context.decodeAudioData(await file.arrayBuffer());if(token!==epoch)return;if(decoded.duration>100)throw new Error('Use a take no longer than 100 seconds.');const audio=new Float32Array(decoded.length);for(let c=0;c<decoded.numberOfChannels;c++){const channel=decoded.getChannelData(c);for(let i=0;i<audio.length;i++)audio[i]+=channel[i]/decoded.numberOfChannels;}raw={audio,sampleRate:decoded.sampleRate};await rerender();status('Existing recording loaded for acoustic tuning. Its speaker has not been changed or cloned.');});action('stop',()=>{++epoch;++renderEpoch;clearTimeout(renderTimer);stopRender();stopMedia();busy=false;buttons();status('Stopped. Any late generation result will be discarded.');});
action('reset',()=>{tuning=normalizeTuning(selected?.tuning||{...DEFAULT_TUNING,pace:selected?.pace??1});synthesis={...synthDefaults,exaggeration:selected?.exaggeration??.5,...selected?.synthesis};fillControls();persist();invalidate('Profile defaults restored. Generate a fresh audition.');});
action('download',async()=>{if(!rendered)throw new Error('Generate or finish rendering an audition first.');download(rendered.blob,`${selected.id}-tuned.wav`);status('Tuned WAV download started.');});
action('addVoice',async()=>{const file=await validateReference($('referenceFile').files[0]);let meta={};if($('metadataFile').files[0]){if($('metadataFile').files[0].size>100000)throw new Error('Metadata JSON must be smaller than 100 KB.');meta=JSON.parse(await $('metadataFile').files[0].text());}const name=$('profileName').value.trim()||meta.name,owner=$('profileOwner').value.trim()||meta.owner;if(!name||!owner)throw new Error('Enter a profile name and owner.');const pkg=await voiceRegistry.save({...meta,id:freshId(name),name,owner,provider:'chatterbox',gender:$('profileGender').value,source:'USER_LOCAL',packageType:'CLONED_REFERENCE',referenceUrl:null,referenceSha256:null,pace:tuning.pace,exaggeration:synthesis.exaggeration,tuning:{...tuning},synthesis:{...synthesis}},file);await refresh(pkg.id);status('Your new speaker profile is saved locally. Export it to move it to another device.');});
action('saveCopy',async()=>{if(!referenceBlob||isHosted())throw new Error('Select a local reference voice first.');const name=selected.name+' · Custom';const pkg=await voiceRegistry.save({...selected,id:freshId(name),name,source:'USER_LOCAL',packageType:'CLONED_REFERENCE',referenceUrl:null,referenceSha256:null,pace:tuning.pace,exaggeration:synthesis.exaggeration,tuning:{...tuning},synthesis:{...synthesis}},referenceBlob);await refresh(pkg.id);status('Saved a new custom profile with this speaker and tuning.');});
action('exportVoice',async()=>{if(!selected)throw new Error('Select a voice profile first.');const snapshot={id:selected.id,hosted:isHosted(),tuning:{...tuning},synthesis:{...synthesis}};const pkg=await voiceRegistry.exportPortable(snapshot.id);if(pkg.metadata)pkg.metadata={...pkg.metadata,tuning:snapshot.tuning,synthesis:snapshot.synthesis,pace:snapshot.tuning.pace,exaggeration:snapshot.synthesis.exaggeration};download(new Blob([JSON.stringify(pkg,null,2)],{type:'application/json'}),`${snapshot.id}.voice-package.json`);status(snapshot.hosted?'Hosted profile package downloaded. Generation requires an authorized provider account on the target host.':'Portable package download started, including reference audio and current tuning.');});
action('removeVoice',async()=>{if(!selected||!['USER_LOCAL','RESEMBLE_HOSTED'].includes(selected.source))throw new Error('Built-in profiles cannot be removed.');const id=selected.id;await voiceRegistry.remove(id);try{localStorage.removeItem(`leeway-studio:${id}`);}catch{}hosted=hosted.filter(p=>p.id!==id);selected=null;await refresh('agent-lee-voice-one');status('Profile removed from this browser. Exported packages and provider voices are unchanged.');});
action('importVoice',async()=>{const file=$('packageFile').files[0];if(!file||file.size>22000000)throw new Error('Choose a portable JSON package smaller than 22 MB.');const pkg=await voiceRegistry.importPortable(JSON.parse(await file.text()));try{localStorage.removeItem(`leeway-studio:${pkg.id}`);}catch{}await refresh(pkg.id);status(`Imported ${pkg.name}.`);});
action('refreshHosted',async()=>{const button=$('refreshHosted');button.disabled=true;try{const result=await api('/api/provider/status');if(!result.resemble?.configured)throw new Error('Set RESEMBLE_API_KEY in the Python studio server environment, then refresh.');const found=[];let page=1,pages=1;do{const result=await api(`/api/resemble/voices?page=${page}`);found.push(...(result.voices||[]));pages=Math.min(Number(result.numPages)||1,50);page++;}while(page<=pages);hosted=[...new Map(found.map(p=>[p.id,p])).values()];drawList();$('hostedState').textContent=`Connected · ${hosted.length} account voices available. Generation uses account credits.`;status('Provider catalog refreshed from your connected account.');}catch(error){$('hostedState').textContent=error.message;throw error;}finally{button.disabled=false;}});
$('referencePlayer').onplay=()=>{$('outputPlayer').pause();};$('outputPlayer').onplay=()=>{$('referencePlayer').pause();};
addEventListener('beforeunload',()=>{stopRender();voice.stop();if(referenceURL)URL.revokeObjectURL(referenceURL);if(outputURL)URL.revokeObjectURL(outputURL);});
refresh().catch(fail);
