/* REGION: LEEWAY.VOICE.STUDIO; TAG: CANONICAL_STUDIO_EXECUTION_CONTROLS
5WH: WHO=Creator-authorized Voice Fabric Studio; WHAT=audition/stream controls;
WHY=bind the spatial UI to real synthesis and playback; WHERE=existing voice owner;
WHEN=user gesture; HOW=existing provider, DSP worker, epoch cancellation and readback.
AUTHORIZED ROLES: Studio operator. LICENSE: Existing repository terms. */
import {voiceRegistry} from './voice-registry.js';
import {DEFAULT_TUNING,normalizeTuning} from './studio-audio.js';
const $=id=>document.getElementById(id), Voice=globalThis.LeeWayBrowserVoice;
const voice=new Voice({skipDefaultReference:true});
const synthDefaults={exaggeration:.5,temperature:.8,top_p:.95,top_k:50};
const controls=[['pace','Pace',.6,1.6,.01,'×','Independent tempo; 1.15 is 15% faster.'],['pitch','Pitch',-6,6,.1,'st','Shift pitch independently of tempo.'],['bass','Bass',-9,9,.5,'dB','Low-frequency weight.'],['warmth','Warmth',-9,9,.5,'dB','Low-mid body.'],['presence','Presence',-9,9,.5,'dB','Speech definition.'],['air','Air',-9,9,.5,'dB','High-frequency brightness.'],['highpass','Low cut',40,180,5,'Hz','Reduce low rumble.'],['deEss','De-essing',0,1,.05,'','Tame sharp consonants.'],['noiseReduction','Noise reduction',0,1,.05,'','Gentle low-level expansion. Strong settings can soften word endings.'],['compression','Compression',1,4,.1,':1','Even out vocal dynamics.'],['gain','Output gain',-9,6,.5,'dB','Adjust final level.']];
const synthControls=[['exaggeration','Expression',0,1,.05,'','Style exaggeration.'],['temperature','Temperature',.5,1,.01,'','Sampling variation.'],['top_p','Top P · unavailable',.5,1,.01,'','Unsupported by the pinned browser runtime; this control is disabled.'],['top_k','Top K',10,100,1,'','Sampling candidate count.']];
let packages=[],hosted=[],localProfiles=[],localStatus=null,localPollTimer=null,localPolls=0,runtimeChosen=false,selected=null,referenceBlob=null,raw=null,rawLabel='Generated audition',rendered=null,tuning={...DEFAULT_TUNING},synthesis={...synthDefaults},epoch=0,selectionEpoch=0,renderEpoch=0,busy=false,preparing=false,renderTimer,referenceURL,outputURL,renderWorker,renderReject,renderDeadline,resumeAfterRender=false,resumeFraction=0;
let studioPhase='idle',generationAbort=null,streamFinish=null,beforePlay=null;
const monotonic=()=>globalThis.performance?.now?.()??Date.now();
function studioEvent(type,detail={}){
 if(typeof document.dispatchEvent==='function'&&typeof CustomEvent==='function')document.dispatchEvent(new CustomEvent('leeway:studio',{detail:{type,at:new Date().toISOString(),epoch,voicePackageId:selected?.id,runtime:$('runtime').value,...detail}}));
}
function phase(value){studioPhase=value;studioEvent('phase',{phase:value});}
function interruptStudio(message='Interrupted. Queued and late speech are discarded.'){
 ++epoch;++renderEpoch;generationAbort?.abort();generationAbort=null;streamFinish?.(new DOMException('Speech interrupted','AbortError'));streamFinish=null;clearTimeout(renderTimer);stopRender();stopMedia();busy=false;phase('interrupted');buttons();status(message);studioEvent('interrupt');
}
const isHosted=()=>!!selected?.voiceUuid;
const supportsLocal=()=>selected?.provider==='kokoro'||selected?.id==='agent-lee-voice-one';
const localReady=()=>selected?.provider==='kokoro'?(!!localStatus?.kokoro?.ready&&(!localStatus.kokoro.voices||localStatus.kokoro.voices.includes(selected.voiceId))):selected?.id==='agent-lee-voice-one'&&!!localStatus?.xtts?.ready;
const usesLocal=()=>!isHosted()&&$('runtime').value==='local';
const allProfiles=()=>[...new Map([...packages,...hosted,...localProfiles].map(pkg=>[pkg.id,pkg])).values()];
function updateRuntime(chooseDefault=false){const select=$('runtime'),local=select.querySelector('[value="local"]'),browser=select.querySelector('[value="browser"]');local.disabled=!supportsLocal()||!localReady();browser.disabled=selected?.provider==='kokoro';select.disabled=isHosted();if(chooseDefault&&!runtimeChosen&&!busy)select.value=supportsLocal()?'local':'browser';if(selected?.provider==='kokoro')select.value='local';$('runtimeState').textContent=isHosted()?'This hosted voice uses your connected Resemble account.':usesLocal()?localReady()?'Local engine ready. Synthesis sampling is fixed; all acoustic dials remain available in your browser.':localEngineMessage():supportsLocal()?'Optional browser synthesis. Choose the local server when available to avoid the browser model download.':'Custom reference profiles use the optional Chatterbox browser engine. They are not substituted with a fixed server voice.';document.querySelector('.model-box').hidden=isHosted()||usesLocal();buttons();}
const status=(message,error=false)=>{$('status').textContent=message;$('status').classList.toggle('error',error);};
const safeRead=key=>{try{return JSON.parse(localStorage.getItem(key));}catch{return null;}};
function persist(){studioEvent('draft-change');try{localStorage.setItem('leeway-studio-selected',JSON.stringify(selected?.id));if(selected)localStorage.setItem(`leeway-studio:${selected.id}`,JSON.stringify({tuning,synthesis}));}catch{status('Browser storage is unavailable. Export your package to preserve it.');}}
function buttons(){ playbackButtons();$('cancelPrepare').hidden=!preparing;$('generate').disabled=!selected||busy||(!isHosted()&&!usesLocal()&&preparing)||(!isHosted()&&(usesLocal()?!localReady():!voice.ready));$('prepare').disabled=isHosted()||preparing||voice.ready;$('prepare').textContent=voice.ready?'Browser model ready':'Prepare browser model';$('generate').textContent=isHosted()?'Generate with Resemble · uses account credits':usesLocal()?'Generate with local engine':'Generate audition';$('download').disabled=!rendered||busy;$('saveCopy').disabled=!selected||isHosted()||(!referenceBlob&&selected.provider!=='kokoro');$('exportVoice').disabled=!selected;$('removeVoice').disabled=!selected||!['USER_LOCAL','RESEMBLE_HOSTED','MODEL_LOCAL'].includes(selected.source);for(const [key]of synthControls){$(key).disabled=isHosted()||usesLocal()||key==='top_p'||(key==='exaggeration'&&voice.capabilities?.exaggeration===false);$(`${key}Number`).disabled=isHosted()||usesLocal()||key==='top_p'||(key==='exaggeration'&&voice.capabilities?.exaggeration===false);}}
function stopRender(){clearTimeout(renderDeadline);if(renderWorker){renderWorker.terminate();renderWorker=null;renderReject?.(new DOMException('Rendering cancelled','AbortError'));renderReject=null;}}
function renderOffThread(raw,tuning){stopRender();return new Promise((resolve,reject)=>{renderReject=reject;const worker=renderWorker=new Worker(new URL('./studio-render.worker.js',import.meta.url),{type:'module'});worker.onmessage=({data})=>{if(renderWorker!==worker)return;clearTimeout(renderDeadline);worker.terminate();renderWorker=null;renderReject=null;data.error?reject(new Error(data.error)):resolve(data.result);};worker.onerror=()=>{if(renderWorker!==worker)return;clearTimeout(renderDeadline);worker.terminate();renderWorker=null;renderReject=null;reject(new Error('Audio processing worker failed. Select the profile again to retry.'));};renderDeadline=setTimeout(()=>{if(renderWorker!==worker)return;worker.terminate();renderWorker=null;renderReject=null;reject(new Error('Audio processing timed out. Select the profile again to retry.'));},30000);worker.postMessage({raw,tuning});});}
function stopMedia(){resumeAfterRender=false;resumeFraction=0;generationAbort?.abort();generationAbort=null;streamFinish?.(new DOMException('Speech stopped','AbortError'));streamFinish=null;voice.stop();$('outputPlayer').pause();$('referencePlayer').pause();globalThis.LeeWayStudioMonitor?.cut();}
function invalidate(message){phase('idle');++epoch;++renderEpoch;clearTimeout(renderTimer);stopRender();stopMedia();busy=false;raw=null;rawLabel='Generated audition';rendered=null;if(outputURL)URL.revokeObjectURL(outputURL);outputURL=null;$('outputPlayer').removeAttribute('src');$('outputPlayer').load();$('renderState').textContent=message;buttons();}
function paintDial(key,value,min,max,unit){const dial=$(key);dial.value=value;dial.style.setProperty('--angle',`${-135+270*(value-min)/(max-min)}deg`);dial.setAttribute('aria-valuenow',String(value));dial.setAttribute('aria-valuetext',`${value} ${unit}`);$(`${key}Number`).value=value;}
function updateControl(key,value,kind,min,max,step,unit){if(studioPhase==='streaming')interruptStudio('Stream stopped before changing tuning. Generate to hear the new settings.');const precision=(String(step).split('.')[1]||'').length;value=Number(Math.max(min,Math.min(max,Math.round(value/step)*step)).toFixed(precision));if((kind==='dsp'?tuning:synthesis)[key]===value){paintDial(key,value,min,max,unit);return;}(kind==='dsp'?tuning:synthesis)[key]=value;paintDial(key,value,min,max,unit);persist();if(kind==='dsp'){const player=$('outputPlayer');if(!player.paused){resumeAfterRender=true;resumeFraction=Number.isFinite(player.duration)&&player.duration>0?player.currentTime/player.duration:0;}++renderEpoch;rendered=null;player.pause();buttons();if(raw){$('renderState').textContent='Updating acoustic processing…';$('dockHint').textContent='Rendering your adjustment…';clearTimeout(renderTimer);renderTimer=setTimeout(()=>rerender().catch(fail),180);}}else pendingSynthesis('Synthesis settings changed. Current sample kept; Generate applies the new settings.');}
function createControls(items,parent,kind){for(const [key,label,min,max,step,unit,hint]of items){const box=document.createElement('div');box.className='control dial-control';box.innerHTML=`<label id="${key}Label" class="dial-label" for="${key}Number">${label}</label><button type="button" id="${key}" class="rotary" role="slider" aria-labelledby="${key}Label" aria-describedby="${key}Hint" aria-valuemin="${min}" aria-valuemax="${max}" aria-valuenow="${min}" title="${hint}"></button><div class="dial-value"><input id="${key}Number" type="number" min="${min}" max="${max}" step="${step}" aria-label="${label} value"><span class="dial-unit">${unit}</span></div><p id="${key}Hint" class="hint">${hint}</p>`;$(parent).append(box);const dial=$(key),number=$(`${key}Number`);const commit=value=>updateControl(key,value,kind,min,max,step,unit);number.addEventListener('change',event=>{if(event.target.value!==''&&Number.isFinite(Number(event.target.value)))commit(Number(event.target.value));else paintDial(key,(kind==='dsp'?tuning:synthesis)[key],min,max,unit);});dial.addEventListener('keydown',event=>{if(dial.disabled)return;let value=Number(dial.value),change=step*(event.shiftKey?10:1);if(['ArrowUp','ArrowRight'].includes(event.key))value+=change;else if(['ArrowDown','ArrowLeft'].includes(event.key))value-=change;else if(event.key==='Home')value=min;else if(event.key==='End')value=max;else if(event.key==='PageUp')value+=(max-min)/10;else if(event.key==='PageDown')value-=(max-min)/10;else return;event.preventDefault();commit(value);});let drag=null;dial.addEventListener('pointerdown',event=>{if(dial.disabled||event.button!==0)return;event.preventDefault();dial.focus();drag={id:event.pointerId,x:event.clientX,y:event.clientY,value:Number(dial.value)};dial.setPointerCapture(event.pointerId);});dial.addEventListener('pointermove',event=>{if(!drag||event.pointerId!==drag.id)return;const delta=event.clientX-drag.x+drag.y-event.clientY;commit(drag.value+delta*(max-min)/(event.shiftKey?1600:200));});const endDrag=()=>{drag=null;};dial.addEventListener('pointerup',endDrag);dial.addEventListener('pointercancel',endDrag);dial.addEventListener('lostpointercapture',endDrag);dial.addEventListener('focus',()=>{$('dockHint').textContent=hint;});}}
function fillControls(){for(const [key,label,min,max,step,unit]of controls)paintDial(key,tuning[key],min,max,unit);for(const [key,label,min,max,step,unit]of synthControls)paintDial(key,synthesis[key],min,max,unit);}
function playbackButtons(){const player=$('outputPlayer'),ready=!!rendered;const playing=!player.paused&&!player.ended;$('playPause').disabled=!ready&&!resumeAfterRender;$('playPause').textContent=playing?'Ⅱ Pause':resumeAfterRender?'Ⅱ Pause pending':'▶ Play';$('playPause').setAttribute('aria-label',playing||resumeAfterRender?'Pause audition':'Play audition');$('restartPlayback').disabled=!ready;$('seek').disabled=!ready;}
function clockTime(value){if(!Number.isFinite(value))return '0:00';return `${Math.floor(value/60)}:${String(Math.floor(value%60)).padStart(2,'0')}`;}
function playbackPosition(){const p=$('outputPlayer');$('seek').value=p.duration>0?100*p.currentTime/p.duration:0;$('playbackTime').textContent=`${clockTime(p.currentTime)} / ${clockTime(p.duration)}`;}
async function playRendered(restart=false){if(!rendered)return;const token=epoch,take=rendered;const player=$('outputPlayer');if(restart||player.ended)player.currentTime=0;if(beforePlay)await beforePlay(player);if(token!==epoch||take!==rendered)return;await player.play();if(token!==epoch||take!==rendered){player.pause();return;}phase('speaking');studioEvent('playback-start',{source:rawLabel,sampleRate:take.sampleRate});playbackButtons();}function drawList(){const query=$('search').value.toLowerCase();$('voiceList').replaceChildren();const all=allProfiles().filter(pkg=>$('showPresets').checked||pkg.source!=='DELIVERY_PRESET');$('voiceCount').textContent=String(all.length);const visible=all.filter(pkg=>[pkg.name,pkg.id,pkg.gender,pkg.provider,pkg.source].join(' ').toLowerCase().includes(query));const group=pkg=>pkg.id==='agent-lee-voice-one'?0:pkg.gender==='female'?1:pkg.gender==='male'?2:3;visible.sort((a,b)=>group(a)-group(b)||a.name.localeCompare(b.name));let previous=-1;for(const pkg of visible){const category=group(pkg);if(category!==previous){const heading=document.createElement('h3');heading.className='voice-group-title';heading.textContent=["Agent Lee",`Female voices · ${visible.filter(p=>group(p)===1).length}`,`Male voices · ${visible.filter(p=>group(p)===2).length}`,'Other profiles'][category];$('voiceList').append(heading);previous=category;}const button=document.createElement('button');button.className='voice-card';button.setAttribute('aria-pressed',String(pkg.id===selected?.id));const title=document.createElement('strong');title.textContent=pkg.name;const subtitle=document.createElement('small');subtitle.textContent=`${pkg.gender||'Gender unspecified'} · ${pkg.provider} · ${pkg.voiceUuid?'Hosted account voice':pkg.provider==='kokoro'?'Distinct local speaker':pkg.source==='DELIVERY_PRESET'?'Delivery preset / same default speaker':'Reference speaker'}\n${pkg.id}`;button.append(title,subtitle);button.onclick=()=>select(pkg.id).catch(fail);$('voiceList').append(button);}}async function refresh(id){packages=await voiceRegistry.list();drawList();const next=id||selected?.id||safeRead('leeway-studio-selected');await select(allProfiles().find(p=>p.id===next)?.id||packages[0]?.id);}
async function select(id){const pkg=allProfiles().find(p=>p.id===id);if(!pkg)return;selected=pkg;runtimeChosen=false;referenceBlob=null;invalidate('No generated audition for this selection.');const token=++selectionEpoch,previewEpoch=epoch;const saved=safeRead(`leeway-studio:${id}`);tuning=normalizeTuning({...DEFAULT_TUNING,pace:pkg.pace??1,...pkg.tuning,...saved?.tuning});synthesis={...synthDefaults,exaggeration:pkg.exaggeration??.5,...pkg.synthesis,...saved?.synthesis};fillControls();persist();drawList();$('selectedTitle').textContent=pkg.name;$('dockSpeaker').textContent=pkg.name;$('dockSpeaker').title=pkg.name;$('dockSpeakerMeta').textContent=`${pkg.gender||'Gender unspecified'} · ${pkg.provider}`;$('selectedMeta').textContent=`${pkg.id} · ${pkg.provider} · ${pkg.gender||'Gender unspecified'}`;$('selectedDescription').textContent=pkg.description||'';$('sourceInfo').textContent=`Source: ${pkg.source||'User reference'}${pkg.referenceSha256?' · SHA-256: '+pkg.referenceSha256:''}`;$('modelState').textContent=isHosted()?'Hosted synthesis uses your connected Resemble account. Local Chatterbox sampling controls do not apply.':voice.ready?'Browser model loaded. The selected speaker reference is applied before each generation.':'First model download approximately 1.5 GB. Prepare explicitly to begin.';$('integrationCode').textContent=`import {voiceRegistry} from './src/voice-registry.js';\n// Import the portable JSON file on the target host:\nconst profile = await voiceRegistry.importPortable(packageJSON);\nconst reference = await voiceRegistry.audio(profile.id);\n// Apply profile.tuning with studio-audio.js after synthesis.\n// Selected profile ID: ${pkg.id}`;if(referenceURL)URL.revokeObjectURL(referenceURL);referenceURL=null;$('referencePlayer').removeAttribute('src');$('referencePlayer').load();document.querySelector('label[for="referencePlayer"]').textContent=pkg.provider==='kokoro'?'Preview of this speaker':'Original speaker reference';updateRuntime(true);status(`Selected ${pkg.name}.`);if(pkg.provider==='kokoro'){await loadSpeakerPreview(pkg,token);return;}
if(isHosted()){
 if(pkg.previewUrl)await loadSpeakerPreview(pkg,token);
 else {$('renderState').textContent='This account voice has no preview. Generate an audition to enable Play.';$('dockHint').textContent='No provider preview · Generate an audition.';}
 return;
}
if(pkg.id==='agent-lee-voice-one'){
 prepareReference(pkg,token,previewEpoch,false).catch(error=>{if(token===selectionEpoch)$('sourceInfo').textContent+=' · Clone reference unavailable; preview remains adjustable.';});
 await loadSpeakerPreview({...pkg,previewUrl:'voices/agent-lee-preview.wav'},token,false);
}else await prepareReference(pkg,token,previewEpoch);
}
async function prepareReference(pkg,selection,generation,preview=true){
 const blob=await voiceRegistry.audio(pkg.id);
 if(selection!==selectionEpoch)return;
 if(!blob)throw new Error('This profile has no reference recording. Import its portable package again.');
 referenceBlob=blob;referenceURL=URL.createObjectURL(blob);$('referencePlayer').src=referenceURL;buttons();
 if(preview)await loadPreviewBlob(blob,'Reference recording · tuning preview',selection,generation);
}
async function loadPreviewBlob(blob,label,selection,generation=epoch){
 // Offline decoding cannot wait for browser permission to start an audio device.
 const context=new OfflineAudioContext(1,1,24000);
 const decoded=await context.decodeAudioData(await blob.arrayBuffer());
 if(selection!==selectionEpoch||generation!==epoch)return;
 if(!decoded.length||decoded.duration>100)throw new Error('Preview must contain audio no longer than 100 seconds.');
 const audio=new Float32Array(decoded.length);
 for(let c=0;c<decoded.numberOfChannels;c++){const channel=decoded.getChannelData(c);for(let i=0;i<audio.length;i++)audio[i]+=channel[i]/decoded.numberOfChannels;}
 raw={audio,sampleRate:decoded.sampleRate};rawLabel=label;await rerender();
 if(selection===selectionEpoch&&generation===epoch)status(`${selected.name} ready. Press Play and adjust the acoustic dials. Generate uses your own text.`);
}
function pendingSynthesis(message){
 if(busy){interruptStudio('Pending generation stopped after draft change.');}
 // Editing future text/sampling must not remove the current adjustable recording.
 $('dockHint').textContent=raw?'Current sample remains playable · Generate to hear your new text/settings.':'Select a profile sample, or Generate an audition.';
 status(message);buttons();
}

async function rerender({autoplay=true}={}){if(!raw)return;const token=++renderEpoch;const generation=epoch;const result=await renderOffThread(raw,normalizeTuning(tuning));if(token!==renderEpoch||generation!==epoch)return;rendered=result;const shouldPlay=autoplay&&(resumeAfterRender||$('autoAudition').checked),position=$('autoAudition').checked?0:resumeFraction;resumeAfterRender=false;resumeFraction=0;if(outputURL)URL.revokeObjectURL(outputURL);outputURL=URL.createObjectURL(result.blob);const player=$('outputPlayer');player.src=outputURL;player.onloadedmetadata=()=>{if(token!==renderEpoch||generation!==epoch)return;if(position>0)player.currentTime=Math.min(position*player.duration,Math.max(0,player.duration-.01));playbackPosition();if(shouldPlay)playRendered().catch(error=>{status(`Audio is ready. Press Play to start playback: ${error.message}`);});};$('renderState').textContent=`${rawLabel} · ${(result.audio.length/result.sampleRate).toFixed(1)} seconds · ${result.sampleRate.toLocaleString()} Hz · current acoustic settings rendered into WAV.`;$('dockHint').textContent=rawLabel.startsWith('Speaker preview')?'Speaker preview · fixed sample text. Generate to hear your own text.':'Current tuning is rendered. Press Play to audition.';buttons();}async function api(url,options){const response=await fetch(url,options);if(!response.ok){if(response.status===404)throw new Error('Voice adapter unavailable. Start the Python studio server. Resemble additionally requires RESEMBLE_API_KEY; static hosting supports browser synthesis only.');let message;try{message=(await response.json()).error;}catch{}throw new Error(message||`Provider request failed (${response.status}).`);}return response.json();}
function synthesisSnapshot(){return {profile:{...selected},local:usesLocal(),hosted:isHosted(),synthesis:{...synthesis},tuning:normalizeTuning(tuning),reference:referenceBlob};}
async function decodeTake(bytes,sourceRate){if(!Number.isInteger(sourceRate)||sourceRate<8000||sourceRate>192000)throw new Error('Synthesis provider did not report a supported sample rate.');const context=new OfflineAudioContext(1,1,sourceRate);const decoded=await context.decodeAudioData(bytes);if(!decoded.length||decoded.duration>100)throw new Error('Voice engine returned empty audio or a take longer than 100 seconds.');const audio=new Float32Array(decoded.length);for(let c=0;c<decoded.numberOfChannels;c++){const channel=decoded.getChannelData(c);for(let i=0;i<audio.length;i++)audio[i]+=channel[i]/decoded.numberOfChannels;}return {audio,sampleRate:decoded.sampleRate};}
async function prepareSynthesis(snapshot,token){
 if(snapshot.local&&!localReady())throw new Error('The selected local engine is not ready. Refresh its status.');
 if(!snapshot.local&&!snapshot.hosted){if(!voice.ready)throw new Error('Prepare the browser model first.');if(!snapshot.reference)throw new Error('Wait for the selected reference recording.');await voice.setReference(snapshot.reference);if(token!==epoch)throw new DOMException('Obsolete voice reference','AbortError');}
}
async function synthesizePart(text,snapshot,token){
 const started=monotonic();let result;
 if(snapshot.local||snapshot.hosted){
  const response=await api(snapshot.local?'/api/local/synthesize':'/api/resemble/synthesize',{method:'POST',signal:generationAbort?.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot.local?{voicePackageId:snapshot.profile.provider==='kokoro'?'kokoro-'+snapshot.profile.voiceId:snapshot.profile.id,text}:{voiceUuid:snapshot.profile.voiceUuid,text})});
  if(token!==epoch)throw new DOMException('Obsolete speech','AbortError');
  const bytes=Uint8Array.from(atob(response.audioContent),c=>c.charCodeAt(0));result=await decodeTake(bytes.buffer,response.sampleRate);
 }else{const part=await voice.request('generate',{text,...snapshot.synthesis});result={audio:part.audio instanceof Float32Array?part.audio:new Float32Array(part.audio),sampleRate:part.sampleRate};}
 if(token!==epoch)throw new DOMException('Obsolete speech','AbortError');
 if(!result.audio.length||!Number.isFinite(result.sampleRate)||result.sampleRate<=0)throw new Error('Voice engine returned invalid audio.');
 studioEvent('synthesis-complete',{generationMs:Math.round(monotonic()-started),sampleRate:result.sampleRate,samples:result.audio.length,provider:snapshot.profile.provider});return result;
}
function combineParts(parts){const sampleRate=parts[0]?.sampleRate;if(parts.some(part=>part.sampleRate!==sampleRate))throw new Error('Generated segments have inconsistent sample rates.');const length=parts.reduce((n,p)=>n+p.audio.length,0);if(!length||length/sampleRate>100)throw new Error('Use a shorter audition; rendered audio is bounded to 100 seconds.');const audio=new Float32Array(length);let offset=0;for(const part of parts){audio.set(part.audio,offset);offset+=part.audio.length;}return {audio,sampleRate};}
async function generate(){
 if(!selected||busy)return;const text=$('speechText').value.trim();if(!text)throw new Error('Enter some audition text.');
 const snapshot=synthesisSnapshot();invalidate('Generating a new audition…');const token=epoch;generationAbort=new AbortController();busy=true;phase('generating');buttons();const started=monotonic();
 try{await prepareSynthesis(snapshot,token);const chunks=snapshot.local||snapshot.hosted?[text]:Voice.chunks(text);if(chunks.length>60)throw new Error('Use a shorter audition text.');const parts=[];
  for(let i=0;i<chunks.length;i++){status(`Generating ${snapshot.profile.name} · segment ${i+1} of ${chunks.length}…`);parts.push(await synthesizePart(chunks[i],snapshot,token));if(token!==epoch)return;}
  raw=combineParts(parts);await rerender();if(token===epoch){phase('idle');status('Audition ready. Press Play to listen, tune or download.');studioEvent('generation-complete',{generationMs:Math.round(monotonic()-started)});}
 }finally{if(token===epoch){busy=false;generationAbort=null;buttons();}}
}
async function playStreamPart(part,snapshot,token){
 const result=await renderOffThread(part,snapshot.tuning);if(token!==epoch)throw new DOMException('Obsolete speech','AbortError');
 const player=$('outputPlayer');player.onloadedmetadata=null;if(outputURL)URL.revokeObjectURL(outputURL);outputURL=URL.createObjectURL(result.blob);player.src=outputURL;
 if(beforePlay)await beforePlay(player);if(token!==epoch)throw new DOMException('Obsolete playback','AbortError');
 return new Promise((resolve,reject)=>{let done=false;const finish=error=>{if(done)return;done=true;player.removeEventListener('ended',ended);player.removeEventListener('error',failed);generationAbort?.signal.removeEventListener('abort',aborted);if(streamFinish===finish)streamFinish=null;error?reject(error):resolve();};const ended=()=>finish(),failed=()=>finish(new Error('Streaming audio playback failed.')),aborted=()=>finish(new DOMException('Speech interrupted','AbortError'));streamFinish=finish;player.addEventListener('ended',ended,{once:true});player.addEventListener('error',failed,{once:true});generationAbort?.signal.addEventListener('abort',aborted,{once:true});player.play().then(()=>{if(token!==epoch){player.pause();finish(new DOMException('Obsolete playback','AbortError'));}else studioEvent('stream-playback-start',{sampleRate:result.sampleRate});}).catch(finish);});
}
async function streamAudition(){
 if(!selected||busy)return;const text=$('speechText').value.trim();if(!text)throw new Error('Enter some audition text.');
 const snapshot=synthesisSnapshot();const chunks=Voice.chunks(text);if(!chunks.length||chunks.length>60)throw new Error('Use 1–60 speech segments.');
 invalidate('Streaming the selected voice…');const token=epoch;generationAbort=new AbortController();busy=true;phase('streaming');buttons();const started=monotonic();let first=true;
 try{await prepareSynthesis(snapshot,token);const parts=[];for(let i=0;i<chunks.length;i++){
   status(`Streaming ${snapshot.profile.name} · segment ${i+1} of ${chunks.length}…`);const part=await synthesizePart(chunks[i],snapshot,token);parts.push(part);combineParts(parts);
   if(first){studioEvent('first-audio-ready',{latencyMs:Math.round(monotonic()-started)});first=false;}
   await playStreamPart(part,snapshot,token);if(token!==epoch)return;
  }
  raw=combineParts(parts);rawLabel='Streamed audition';await rerender({autoplay:false});if(token===epoch){phase('idle');status('Stream complete. The full take is ready for replay, acoustic tuning and download.');studioEvent('stream-complete',{segments:parts.length,elapsedMs:Math.round(monotonic()-started)});}
 }finally{if(token===epoch){busy=false;generationAbort=null;buttons();}}
}

function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function validateReference(file){if(!file||file.size<1||file.size>15_000_000)throw new Error('Choose a reference audio file smaller than 15 MB.');const context=await voice.audioContext();let decoded;try{decoded=await context.decodeAudioData(await file.arrayBuffer());}catch{throw new Error('This audio format could not be decoded. Try WAV or MP3.');}if(decoded.duration<1||decoded.duration>30)throw new Error('Reference audio must be between 1 and 30 seconds.');return file;}
const freshId=name=>String(name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)+'-'+crypto.randomUUID().slice(0,8);
function fail(error){if(error.name!=='AbortError'){phase('error');studioEvent('error',{message:error.message||String(error)});status(error.message||String(error),true);if(!rendered)$('dockHint').textContent=error.message||String(error);}buttons();}
function action(id,handler){$(id).onclick=()=>Promise.resolve().then(handler).catch(fail);}
createControls(controls,'dspControls','dsp');createControls(synthControls,'synthesisControls','synth');fillControls();
$('search').oninput=drawList;$('speechText').oninput=()=>pendingSynthesis('Text changed. Current sample kept; Generate speaks the new text.');
action('prepare',async()=>{phase('preparing');preparing=true;buttons();$('modelProgress').hidden=false;try{await voice.load(progress=>{const text=progress.message||`${progress.status||'Loading'} ${progress.file||'browser model'}`;status(text);if(Number.isFinite(progress.progress)){$('modelProgress').max=100;$('modelProgress').value=progress.progress;}else $('modelProgress').removeAttribute('value');});$('modelState').textContent=`Browser model ready · ${voice.device||'local inference'}.`;status('Model ready. Choose a speaker and generate an audition.');}finally{preparing=false;if(studioPhase==='preparing')phase('idle');$('modelProgress').hidden=true;buttons();}});
action('generate',generate);
action('loadTake',async()=>{const file=$('takeFile').files[0];if(!file||file.size>64000000)throw new Error('Choose an audio take smaller than 64 MB.');invalidate('Loading existing recording…');const token=epoch;const context=await voice.audioContext();const decoded=await context.decodeAudioData(await file.arrayBuffer());if(token!==epoch)return;if(decoded.duration>100)throw new Error('Use a take no longer than 100 seconds.');const audio=new Float32Array(decoded.length);for(let c=0;c<decoded.numberOfChannels;c++){const channel=decoded.getChannelData(c);for(let i=0;i<audio.length;i++)audio[i]+=channel[i]/decoded.numberOfChannels;}raw={audio,sampleRate:decoded.sampleRate};rawLabel='Existing recording';await rerender();status('Existing recording loaded for acoustic tuning. Its speaker has not been changed or cloned.');});action('stop',()=>interruptStudio());
action('reset',async()=>{const previousSynthesis={...synthesis};tuning=normalizeTuning({...DEFAULT_TUNING,pace:selected?.pace??1,...selected?.tuning});synthesis={...synthDefaults,exaggeration:selected?.exaggeration??.5,...selected?.synthesis};const samplingChanged=['temperature','top_k',...(voice.capabilities?.exaggeration===false?[]:['exaggeration'])].some(key=>previousSynthesis[key]!==synthesis[key]);fillControls();persist();if(!usesLocal()&&!isHosted()&&samplingChanged){pendingSynthesis('Synthesis defaults restored. Generate to hear new synthesis settings.');}if(raw){const token=epoch,player=$('outputPlayer');if(!player.paused){resumeAfterRender=true;resumeFraction=Number.isFinite(player.duration)&&player.duration>0?player.currentTime/player.duration:0;}clearTimeout(renderTimer);++renderEpoch;rendered=null;player.pause();buttons();$('renderState').textContent='Restoring profile defaults on the current take…';await rerender();if(token===epoch)status('Profile defaults restored on the same audition.');}else{status(busy?'Profile defaults restored. The current generation will use the reset acoustic settings.':'Profile defaults restored. Generate or load an audition to hear them.');buttons();}});
action('download',async()=>{if(!rendered)throw new Error('Generate or finish rendering an audition first.');download(rendered.blob,`${selected.id}-tuned.wav`);status('Tuned WAV download started.');});
action('addVoice',async()=>{const file=await validateReference($('referenceFile').files[0]);let meta={};if($('metadataFile').files[0]){if($('metadataFile').files[0].size>100000)throw new Error('Metadata JSON must be smaller than 100 KB.');meta=JSON.parse(await $('metadataFile').files[0].text());}const name=$('profileName').value.trim()||meta.name,owner=$('profileOwner').value.trim()||meta.owner;if(!name||!owner)throw new Error('Enter a profile name and owner.');const pkg=await voiceRegistry.save({...meta,id:freshId(name),name,owner,provider:'chatterbox',gender:$('profileGender').value,source:'USER_LOCAL',packageType:'CLONED_REFERENCE',referenceUrl:null,referenceSha256:null,pace:tuning.pace,exaggeration:synthesis.exaggeration,tuning:{...tuning},synthesis:{...synthesis}},file);await refresh(pkg.id);status('Your new speaker profile is saved locally. Export it to move it to another device.');});
action('saveCopy',async()=>{if(!selected||isHosted()||(!referenceBlob&&selected.provider!=='kokoro'))throw new Error('Select a local model voice or reference voice first.');const modelVoice=selected.provider==='kokoro',name=selected.name+' · Custom';const pkg=await voiceRegistry.save({...selected,id:freshId(name),name,source:modelVoice?'MODEL_LOCAL':'USER_LOCAL',packageType:modelVoice?'MODEL_VOICE':'CLONED_REFERENCE',referenceUrl:null,referenceSha256:null,pace:tuning.pace,exaggeration:synthesis.exaggeration,tuning:{...tuning},synthesis:{...synthesis}},modelVoice?null:referenceBlob);await refresh(pkg.id);status(modelVoice?'Saved a custom Kokoro profile with the same model speaker and your tuning.':'Saved a new custom profile with this speaker and tuning.');});
action('exportVoice',async()=>{if(!selected)throw new Error('Select a voice profile first.');const snapshot={id:selected.id,hosted:isHosted(),model:selected.provider==='kokoro',tuning:{...tuning},synthesis:{...synthesis}};const pkg=await voiceRegistry.exportPortable(snapshot.id);if(pkg.metadata)pkg.metadata={...pkg.metadata,tuning:snapshot.tuning,synthesis:snapshot.synthesis,pace:snapshot.tuning.pace,exaggeration:snapshot.synthesis.exaggeration};download(new Blob([JSON.stringify(pkg,null,2)],{type:'application/json'}),`${snapshot.id}.voice-package.json`);status(snapshot.hosted?'Hosted profile package downloaded. Generation requires an authorized provider account on the target host.':snapshot.model?'Kokoro profile package downloaded with model voice ID and tuning. The target host needs the Kokoro adapter and model weights; no reference recording is included.':'Portable clone package downloaded, including reference audio and current tuning.');});
action('removeVoice',async()=>{if(!selected||!['USER_LOCAL','RESEMBLE_HOSTED','MODEL_LOCAL'].includes(selected.source))throw new Error('Built-in profiles cannot be removed.');const id=selected.id;await voiceRegistry.remove(id);try{localStorage.removeItem(`leeway-studio:${id}`);}catch{}hosted=hosted.filter(p=>p.id!==id);selected=null;await refresh('agent-lee-voice-one');status('Profile removed from this browser. Exported packages and provider voices are unchanged.');});
action('importVoice',async()=>{const file=$('packageFile').files[0];if(!file||file.size>22000000)throw new Error('Choose a portable JSON package smaller than 22 MB.');const pkg=await voiceRegistry.importPortable(JSON.parse(await file.text()));try{localStorage.removeItem(`leeway-studio:${pkg.id}`);}catch{}await refresh(pkg.id);status(`Imported ${pkg.name}.`);});
action('refreshHosted',async()=>{const button=$('refreshHosted');button.disabled=true;try{const result=await api('/api/provider/status');if(!result.resemble?.configured)throw new Error('Set RESEMBLE_API_KEY in the Python studio server environment, then refresh.');const found=[];let page=1,pages=1;do{const result=await api(`/api/resemble/voices?page=${page}`);found.push(...(result.voices||[]));pages=Math.min(Number(result.numPages)||1,50);page++;}while(page<=pages);hosted=[...new Map(found.map(p=>[p.id,p])).values()];drawList();$('hostedState').textContent=`Connected · ${hosted.length} account voices available. Generation uses account credits.`;status('Provider catalog refreshed from your connected account.');}catch(error){$('hostedState').textContent=error.message;throw error;}finally{button.disabled=false;}});
$('referencePlayer').onplay=async()=>{
 const reference=$('referencePlayer');
 if(busy){const position=reference.currentTime;interruptStudio('Stream interrupted for the reference audition.');const token=epoch;try{if(beforePlay)await beforePlay(reference);if(token!==epoch)return;reference.currentTime=position;await reference.play();if(token!==epoch)reference.pause();}catch(error){fail(error);}}
 else $('outputPlayer').pause();
};$('outputPlayer').onplay=()=>{$('referencePlayer').pause();};
addEventListener('beforeunload',()=>{stopRender();voice.stop();if(referenceURL)URL.revokeObjectURL(referenceURL);if(outputURL)URL.revokeObjectURL(outputURL);});
refresh().then(()=>refreshLocal()).catch(fail);

// Persistent transport beside the tuning dials.
action('playPause',async()=>{const player=$('outputPlayer');if(resumeAfterRender||!player.paused){resumeAfterRender=false;resumeFraction=0;$('autoAudition').checked=false;player.pause();playbackButtons();return;}await playRendered();});
action('restartPlayback',()=>playRendered(true));
$('seek').oninput=()=>{const player=$('outputPlayer');if(Number.isFinite(player.duration))player.currentTime=Number($('seek').value)*player.duration/100;};
for(const event of ['play','pause','ended','loadedmetadata','timeupdate'])$('outputPlayer').addEventListener(event,()=>{playbackButtons();playbackPosition();});
$('autoAudition').onchange=()=>{if(!$('autoAudition').checked)resumeAfterRender=false;status($('autoAudition').checked?'Replay after adjustment enabled. Each completed acoustic change restarts the audition.':'Automatic replay disabled. Press Play whenever you want to audition.');};
function showDialTab(synthesisTab){$('dspPanel').hidden=synthesisTab;$('synthesisPanel').hidden=!synthesisTab;for(const [id,active]of [['acousticTab',!synthesisTab],['synthesisTab',synthesisTab]]){$(id).setAttribute('aria-selected',String(active));$(id).tabIndex=active?0:-1;}measureDock();}
$('acousticTab').onclick=()=>showDialTab(false);$('synthesisTab').onclick=()=>showDialTab(true);
for(const id of ['acousticTab','synthesisTab'])$(id).onkeydown=event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?false:event.key==='End'?true:id==='acousticTab';showDialTab(next);$(next?'synthesisTab':'acousticTab').focus();}};
function measureDock(){document.documentElement.style.setProperty('--dock-height',`${Math.ceil($('tuningDock').getBoundingClientRect().height)}px`);}
new ResizeObserver(measureDock).observe($('tuningDock'));addEventListener('resize',measureDock);measureDock();

async function refreshLocal(){clearTimeout(localPollTimer);try{const response=await fetch('/api/local/status');if(!response.ok)throw new Error('Local engine adapter unavailable. Start the Python studio server and refresh.');localStatus=await response.json();const catalog=await fetch('/api/local/voices');if(catalog.ok){const data=await catalog.json();localProfiles=data.voices||[];drawList();}updateRuntime(true);if((localStatus.kokoro?.state==='loading'||localStatus.xtts?.ready===false)&&localPolls++<100)localPollTimer=setTimeout(()=>refreshLocal().catch(fail),3000);}catch(error){$('runtimeState').textContent=error.message;localStatus=null;buttons();}}
action('refreshLocal',()=>{localPolls=0;return refreshLocal();});
$('runtime').onchange=()=>{runtimeChosen=true;pendingSynthesis('Runtime changed. Current sample kept; Generate uses the selected engine.');updateRuntime();};
$('showPresets').onchange=drawList;
function localEngineMessage(){const engine=selected?.provider==='kokoro'?localStatus?.kokoro:localStatus?.xtts;const name=selected?.provider==='kokoro'?'Kokoro':'Agent Lee XTTS';if(selected?.provider==='kokoro'&&engine?.ready&&engine.voices&&!engine.voices.includes(selected.voiceId))return 'Preview ready for tuning. Restart the updated local engine to generate new text with this added voice.';if(!engine)return `${name} · checking the local service. Browser download is optional.`;return `${name} · ${engine.state||'warming'}. ${engine.message||'Wait for the service to become ready, or refresh its status.'}`;}
async function loadSpeakerPreview(pkg,selection,updateReference=true){
 if(selection!==selectionEpoch)return;
 const generation=epoch,url=pkg.provider==='kokoro'?`voices/kokoro-previews/${encodeURIComponent(pkg.voiceId)}.wav`:pkg.previewUrl;
 if(updateReference)$('referencePlayer').src=url;
 $('renderState').textContent='Loading selected speaker sample…';$('dockHint').textContent='Loading selected speaker sample…';
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
 try{
  const response=await fetch(url,{signal:controller.signal});
  if(!response.ok)throw new Error(`Preview unavailable (${response.status}).`);
  const blob=await response.blob();
  if(selection!==selectionEpoch||generation!==epoch)return;
  await loadPreviewBlob(blob,'Speaker preview · fixed sample text',selection,generation);
 }catch(error){
  if(selection!==selectionEpoch||generation!==epoch)return;
  const message=error.name==='AbortError'?'Preview loading timed out. Select the profile again to retry.':`Could not prepare this profile: ${error.message}`;
  $('renderState').textContent=message;$('dockHint').textContent=message;status(message,true);buttons();
 }finally{clearTimeout(timer);}
}

action('cancelPrepare',async()=>{await voice.cancelLoad();preparing=false;phase('idle');$('modelProgress').hidden=true;$('modelState').textContent='Browser preparation cancelled. Local engines and recording tuning remain available.';buttons();status('Browser model preparation cancelled.');});
// One controller over the existing Studio state; no additional synthesis/voice owner.
globalThis.LeeWayStudioControls={
 snapshot:()=>({phase:studioPhase,selected:selected?{...selected}:null,tuning:{...tuning},synthesis:{...synthesis},runtime:$('runtime').value,busy,preparing,ready:!$('generate').disabled,hasTake:!!rendered,source:rawLabel,epoch}),
 setBeforePlay:handler=>{beforePlay=handler;},
 generate,stream:streamAudition,stop:interruptStudio,play:playRendered,select,
 loadShared:async(id,settings)=>{await select(id);if(selected?.id!==id)throw new Error('Shared voice is not in this Studio catalog.');tuning=normalizeTuning(settings);fillControls();persist();if(raw)await rerender({autoplay:false});},
 reportError:fail,
};
for(const event of ['pause','ended'])$('outputPlayer').addEventListener(event,()=>{if(!busy&&studioPhase==='speaking')phase(event==='ended'?'idle':'paused');});
studioEvent('controller-ready');
